<a href="https://colab.research.google.com/github/dsreliete/Womakerscode-DA-colab/blob/main/%5BNotebook%5D_Python_para_Dados_Numpy_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
                    #cli1 cli2 cli3
acidentes = np.array([[1, 3, 2], #ano1
                    [0, 1, 0],   #ano2
                    [2, 1, 4],   #ano3
                    [0, 0, 0],   #ano4
                    [1, 1, 0]])  #ano5

cada coluna é um cliente e cada linha é o total de aciendentes por cliente por ano

In [4]:
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

Soma de acidentes de todos os clientes por ano

In [5]:
acidentes.sum(axis=1)

array([6, 1, 7, 0, 2])

soma de acidentes por cliente em todos os anos

In [6]:
acidentes.sum(axis=0)

array([4, 6, 6])

In [7]:
acidentes.min() #maior numero de acidentes

0

In [8]:
acidentes.max() #menor numero de acidentes

4

In [9]:
acidentes.max(axis=1) #maior numero de acidentes por ano

array([3, 1, 4, 0, 1])

In [10]:
acidentes.min(axis=1) #menor numero de acidentes por ano

array([1, 0, 1, 0, 0])

In [11]:
acidentes.max(axis=0) #maior numero de acidentes por cliente

array([2, 3, 4])

In [12]:
acidentes.min(axis=0) #menor numero de acidentes por cliente

array([0, 0, 0])

In [13]:
acidentes.mean() #media de acidentes

1.0666666666666667

In [14]:
acidentes.mean(axis=1) #media de acidentes por ano de todos os clientes

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

In [15]:
acidentes.mean(axis=0) #media de acidentes por cliente de todos os anos

array([0.8, 1.2, 1.2])

In [16]:
acidentes.mean(axis=0).shape

(3,)

In [17]:
acidentes.mean(axis=0, keepdims=True) #media de acidentes por cliente de todos os anos mantendo a dimensao

array([[0.8, 1.2, 1.2]])

In [18]:
acidentes.mean(axis=0, keepdims=True).shape

(1, 3)

In [19]:
acidentes.mean(axis=1, keepdims=True) #media de acidentes por ano de todos os clientes mantendo a dimensao

array([[2.        ],
       [0.33333333],
       [2.33333333],
       [0.        ],
       [0.66666667]])

In [20]:
acidentes.mean(axis=1, keepdims=True).shape

(5, 1)

In [21]:
acidentes.mean(axis=1).shape

(5,)

In [22]:
acidentes.cumsum(axis=0) #soma acumulada de acidentes por cliente de todos os anos

array([[1, 3, 2],
       [1, 4, 2],
       [3, 5, 6],
       [3, 5, 6],
       [4, 6, 6]])

In [23]:
acidentes.cumsum(axis=1) #soma acumulada de acidentes por ano de todos os clientes

array([[1, 4, 6],
       [0, 1, 1],
       [2, 3, 7],
       [0, 0, 0],
       [1, 2, 2]])

**Cartela de Bingo 2**


In [24]:
cartela_bingo = np.random.randint(0,10, (4,4))
cartela_bingo

array([[8, 5, 4, 8],
       [3, 4, 5, 3],
       [2, 9, 5, 4],
       [2, 6, 9, 3]])

In [25]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[8, 5, 4, 8],
       [3, 4, 5, 3],
       [2, 9, 5, 4]])

In [26]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

array([[2, 6, 9, 3]])

In [27]:
np.concatenate((cartela_bingo1, cartela_bingo2))

array([[8, 5, 4, 8],
       [3, 4, 5, 3],
       [2, 9, 5, 4],
       [2, 6, 9, 3]])

In [28]:
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [29]:
np.delete(cartela_bingo, 1, axis=1) #eixo 1 é sempre as colunas

array([[8, 4, 8],
       [3, 5, 3],
       [2, 5, 4],
       [2, 9, 3]])

In [30]:
np.delete(cartela_bingo, 1, axis=0) #eixo 0 é sempre as linhas

array([[8, 5, 4, 8],
       [2, 9, 5, 4],
       [2, 6, 9, 3]])

**Aritmetica**

In [31]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr += 3
arr

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2 *= 5
arr2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [33]:
a = np.array([[1, 2, 3], [4,5,6]]) #operaçao permitida pelo numpy pq os arrays a e b tem o mesmo tamanho
b = np.array([[2,2,2], [0,0,1]])
a+b

array([[3, 4, 5],
       [4, 5, 7]])

In [34]:
c = np.array([[1, 2, 3], [4,5,6]])
d = np.array([[2,2,2], [0,0,1]])
a*b

array([[2, 4, 6],
       [0, 0, 6]])

In [35]:
a = np.array([[1, 2, 3], [4,5,6]])
a > 3

array([[False, False, False],
       [ True,  True,  True]])

In [36]:
arr = np.array(["Hello", "Girls", "Womakerscode"]) #aqui eu to verificando se a qtidade de elemento desse vetor é maior q 5
len(arr) > 5


False

In [37]:
vetorizar_len = np.vectorize(len) #vetorizando matriz: aplica uma funcao pra cada elemento de um array. Nesse caso, pra cada elemento do vetor é maior que cinco
vetorizar_len(arr) > 5

array([False, False,  True])

In [38]:
def minha_funcao(x):
  return x**2 + 3*x + 1

funcao_vetorizada = np.vectorize(minha_funcao)
funcao_vetorizada(np.array([1,2,3,4,5]))

array([ 5, 11, 19, 29, 41])

In [39]:
e = np.array([[1, 2], [4,5], [7,8]])

f = np.array([1,0,-1]).reshape(3,1)

e + f

array([[2, 3],
       [4, 5],
       [6, 7]])

In [40]:
arr10 = np.arange(10)
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr10 = np.arange(10).reshape(2,5)
arr10

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [42]:
arr5 = np.array([1,2,3,4,5])
arr5

array([1, 2, 3, 4, 5])

In [43]:
arr10.shape, arr5.shape

((2, 5), (5,))

In [44]:
arr10 + arr5

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14]])

In [45]:
arr10 = np.arange(10).reshape(2,5)
arr10

arr5 = np.array([2,1]).reshape(2,1)
arr5

arr10/arr5

array([[0. , 0.5, 1. , 1.5, 2. ],
       [5. , 6. , 7. , 8. , 9. ]])

### 1. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


### 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

### 3. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


### 4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.

In [46]:
                      #P1 P2 P3
arr_notas = np.array([[1, 2, 1],  #aluno1
                      [1, 2, 1],  #aluno2
                      [1, 2, 1]]) #aluno1
arr_notas

array([[1, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [47]:
arr_notas.shape

(3, 3)