<a href="https://colab.research.google.com/github/dsreliete/Womakerscode-DA-colab/blob/main/%5BNotebook%5D_Python_para_Dados_Numpy_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([2, 4, 6, 7, 8])
arr[1]

4

In [ ]:
arr[2:4]

array([6, 7])

In [ ]:
arr[0]

2

In [ ]:
cartela_bingo = np.array([[16, 10,  3, 15],
                            [14, 23, 17, 27],
                            [ 6, 19,  3,  1],
                            [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

selecional linha de array de 2 dimensoes

In [ ]:
cartela_bingo[3]

array([10,  4, 18, 19])

selecionando coluna de array de 2 dimensoes

In [ ]:
cartela_bingo[:, 1]

array([10, 23, 19,  4])

selecionando linha e coluna de uma array de duas dimensoes

In [ ]:
cartela_bingo[1:3, 0:2]

array([[14, 23],
       [ 6, 19]])

In [ ]:
cartela_bingo[:, 1].shape

(4,)

In [ ]:
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [ ]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [ ]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

axis zero é igual eixo Y

In [ ]:
np.sort(cartela_bingo, axis=0)

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

axis 1 = eixo **x**

In [ ]:
np.sort(cartela_bingo, axis=1)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

## 1.1 Explorando Ecossistemas:
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

**ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie**



*  Selecione a segunda coluna com a quantidade de espécies encontradas e adicione em um array as qtd_especies.
*  De qtd_especies selecione apenas as primeiras 3 quantidades e print
*  Print as 5 últimas quantidades de espécies
*  Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente






In [ ]:
especies = np.array([[747,  89,  33,   5],
                    [623, 123,  32,  13],
                    [501,  22,  49,   2],
                    [116, 101,  42,  10],
                    [297,  56,  69,  22],
                    [613,  64,  27,   7],
                    [295,  84,  29,  14],
                    [692, 105,  72,  16],
                    [229, 103,  35,   5],
                    [374, 124,  70,   1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

In [ ]:
qtd_especies = especies[:, 1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [ ]:
qtd_especies[0:3]

array([ 89, 123,  22])

In [ ]:
qtd_especies[:3]

array([ 89, 123,  22])

pra saber qntas linhas da um shape

In [ ]:
qtd_especies.shape

(10,)

Abaixo eu to pegando os últimos 5 elementos do array simples, qndo eu nao sei qual o tamanho do array

In [ ]:
qtd_especies[-5:]

array([ 64,  84, 105, 103, 124])

aqui eu to excluindo o ultimo elemento ou pegando os primeiros 9

In [ ]:
qtd_especies[:-1]

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103])

ordena elementos da coluna 3 em ordem crescente

In [ ]:
tam_especies_ordenado = np.sort(especies[:, 3])
tam_especies_ordenado

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

ordena elementos da coluna 3 em ordem decrescente


In [ ]:
tam_especies_ordenado2 = np.sort(especies[:, 3])[::-1]
tam_especies_ordenado2

array([22, 16, 14, 13, 10,  7,  5,  5,  2,  1])

## Filtrando Arrays

aqui retorna o resultado da comparacao

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
mask = arr1 % 3 == 0
mask

array([False, False,  True, False, False])

ja aqui retorna o indice do array que corresponde com true a comparacao

In [ ]:
arr1[mask]

array([3])

In [ ]:
pessoas_id_idade = np.array([[1, 22], [2, 21], [3, 27], [4, 26]])
pessoas_id_idade

array([[ 1, 22],
       [ 2, 21],
       [ 3, 27],
       [ 4, 26]])

pega tudo da linha na coluna 1 e verifique se eh maior q 25 = array de uma dimensao

In [ ]:
np.where(pessoas_id_idade[:, 1] > 25)

(array([2, 3]),)

In [ ]:
cartela_bingo = np.array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

array de duas dimensoes retorna true qndo contempla a condicao indicando o indice separadamente. primeiro array e de linhas e o segundo array e de colunas

In [ ]:
np.where(cartela_bingo % 3 == 0)

(array([0, 0, 1, 2, 2, 3]), array([2, 3, 3, 0, 2, 2]))

buscar e substituir: qndo contemplar a condicao substitui por espaco caso contrario manter o valor original


In [ ]:
np.where(cartela_bingo % 3 == 0, " ", cartela_bingo)

array([['16', '10', ' ', ' '],
       ['14', '23', '17', ' '],
       [' ', '19', ' ', '1'],
       ['10', '4', ' ', '19']], dtype='<U21')

## 1.2 Ainda usando o Array de espécies marítimas.

*   Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

*   Usando fency index faça um array que contém apenas dados da espécie com ID 297
*   Usando np.where() faça um array com a linha com dados correspondentes a espécie com 105 representantes encontrados.
*   Considere a profundeza em que o espécie foi encontrada substitua valores maiores que 60 com "Profundo"


Tabela = ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie



In [ ]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1]])

Usando um index booleano crie um array que contém os dados da maior espécie encontrada (considerando o seu tamanho), esse valor corresponde ao valor 22.

In [ ]:
especie_maior_22 = np.where(especies[:, 3] == 22, True, False)
especie_maior_22

array([False, False, False, False,  True, False, False, False, False,
       False])

In [ ]:
especies[especies[:, 3] == 22]

array([[297,  56,  69,  22]])

In [ ]:
mask = especies[:, 0] == 297
especies[mask]

array([[297,  56,  69,  22]])

In [ ]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  72,  16]])

In [ ]:
np.where(especies[:,2] > 60, "Profundo", especies[:,2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U21')

## 1.3 Ainda no conjunto 'especies'.

*   Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
*   Adicione mais uma coluna na no array original agora com o número de espécies encontradas com que indica se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0]
* Faça um array com todas as especies menos com ID 623, 116, 613


In [ ]:
arr = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])
arr

array([[204,  10,  40,  12],
       [392,  11,  81,  11]])

In [ ]:
new_array = np.concatenate((especies, arr))
new_array

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  72,  16],
       [229, 103,  35,   5],
       [374, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [ ]:
new_array.shape

(12, 4)

In [ ]:
arr_encherga = np.array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1])
arr_encherga

array([0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1])

In [ ]:
arr_encherga.shape

(12,)

In [ ]:
arr_encherga = arr_encherga.reshape((12,1))
arr_encherga

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]])

In [ ]:
new_new_array = np.concatenate((new_array, arr_encherga), axis=1)
new_new_array

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

In [ ]:
new_new_array.shape

(12, 5)

In [ ]:
exclude_array = np.delete(new_new_array, [1, 3, 5], axis=0) #exclui linha 1,3, 5
exclude_array

array([[747,  89,  33,   5,   0],
       [501,  22,  49,   2,   0],
       [297,  56,  69,  22,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  72,  16,   0],
       [229, 103,  35,   5,   1],
       [374, 124,  70,   1,   1],
       [204,  10,  40,  12,   0],
       [392,  11,  81,  11,   1]])

Concatenando arrays

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr3 = np.random.randint(10, size=(3, 3))
arr3

arr4 = np.array([["pera", "uva", "maca"]])
np.concatenate((arr3, arr4))

array([['1', '1', '9'],
       ['1', '1', '9'],
       ['5', '3', '3'],
       ['pera', 'uva', 'maca']], dtype='<U21')

concatenando arrays desiquilibrados usando axis

In [ ]:
arr5 = np.random.randint(10, size=(3, 2))
arr5

array([[0, 2],
       [1, 8],
       [8, 5]])

In [ ]:
arr6 = np.array(["pera", "uva", "maca"]).reshape((3,1))
arr6

array([['pera'],
       ['uva'],
       ['maca']], dtype='<U4')

concatenate se importa com dimensao, tem que ser amesma dimensao entre os arrays concatenados

In [ ]:
np.concatenate((arr5, arr6), axis=1)

array([['0', '2', 'pera'],
       ['1', '8', 'uva'],
       ['8', '5', 'maca']], dtype='<U21')

In [ ]:
sala_espera = np.array([[5,30, 56, "Alice"],
                        [6,46, 67, "Fernando"],
                        [7,12, 34, "Clarissa"],
                        [8,11, 90, "Sheldon"]])
sala_espera

array([['5', '30', '56', 'Alice'],
       ['6', '46', '67', 'Fernando'],
       ['7', '12', '34', 'Clarissa'],
       ['8', '11', '90', 'Sheldon']], dtype='<U21')

exclui coluna 1

In [ ]:
np.delete(sala_espera, 1, axis=1)

array([['5', '56', 'Alice'],
       ['6', '67', 'Fernando'],
       ['7', '34', 'Clarissa'],
       ['8', '90', 'Sheldon']], dtype='<U21')

exclui linha 3

In [ ]:
np.delete(sala_espera, 2, axis=0)

array([['5', '30', '56', 'Alice'],
       ['6', '46', '67', 'Fernando'],
       ['8', '11', '90', 'Sheldon']], dtype='<U21')

exclui sem axis

In [ ]:
np.delete(sala_espera, 2)

array(['5', '30', 'Alice', '6', '46', '67', 'Fernando', '7', '12', '34',
       'Clarissa', '8', '11', '90', 'Sheldon'], dtype='<U21')