<a href="https://colab.research.google.com/github/dsreliete/Womakerscode-DA-colab/blob/main/%5BNotebook%5D_Python_para_Dados_Numpy_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
                    #cli1 cli2 cli3
acidentes = np.array([[1, 3, 2], #ano1
                    [0, 1, 0],   #ano2
                    [2, 1, 4],   #ano3
                    [0, 0, 0],   #ano4
                    [1, 1, 0]])  #ano5

cada coluna é um cliente e cada linha é o total de aciendentes por cliente por ano

In [3]:
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

Soma de acidentes de todos os clientes por ano

In [4]:
acidentes.sum(axis=1)

array([6, 1, 7, 0, 2])

soma de acidentes por cliente

In [5]:
acidentes.sum(axis=0)

array([4, 6, 6])

### 1. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


### 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

### 3. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


### 4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.