<a href="https://colab.research.google.com/github/dsreliete/Womakerscode-DA-colab/blob/main/%5BNotebook%5D_Python_para_Dados_Numpy_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
                    #cli1 cli2 cli3
acidentes = np.array([[1, 3, 2], #ano1
                    [0, 1, 0],   #ano2
                    [2, 1, 4],   #ano3
                    [0, 0, 0],   #ano4
                    [1, 1, 0]])  #ano5

cada coluna é um cliente e cada linha é o total de aciendentes por cliente por ano

In [ ]:
acidentes

array([[1, 3, 2],
       [0, 1, 0],
       [2, 1, 4],
       [0, 0, 0],
       [1, 1, 0]])

Soma de acidentes de todos os clientes por ano

In [ ]:
acidentes.sum(axis=1)

array([6, 1, 7, 0, 2])

soma de acidentes por cliente em todos os anos

In [ ]:
acidentes.sum(axis=0)

array([4, 6, 6])

In [ ]:
acidentes.min() #maior numero de acidentes

0

In [ ]:
acidentes.max() #menor numero de acidentes

4

In [ ]:
acidentes.max(axis=1) #maior numero de acidentes por ano

array([3, 1, 4, 0, 1])

In [ ]:
acidentes.min(axis=1) #menor numero de acidentes por ano

array([1, 0, 1, 0, 0])

In [ ]:
acidentes.max(axis=0) #maior numero de acidentes por cliente

In [ ]:
acidentes.min(axis=0) #menor numero de acidentes por cliente

In [ ]:
acidentes.mean() #media de acidentes

1.0666666666666667

In [ ]:
acidentes.mean(axis=1) #media de acidentes por ano de todos os clientes

array([2.        , 0.33333333, 2.33333333, 0.        , 0.66666667])

In [ ]:
acidentes.mean(axis=0) #media de acidentes por cliente de todos os anos

array([0.8, 1.2, 1.2])

In [ ]:
acidentes.mean(axis=0).shape

(3,)

In [ ]:
acidentes.mean(axis=0, keepdims=True) #media de acidentes por cliente de todos os anos mantendo a dimensao

array([[0.8, 1.2, 1.2]])

In [ ]:
acidentes.mean(axis=0, keepdims=True).shape

(1, 3)

In [ ]:
acidentes.mean(axis=1, keepdims=True) #media de acidentes por ano de todos os clientes mantendo a dimensao

array([[2.        ],
       [0.33333333],
       [2.33333333],
       [0.        ],
       [0.66666667]])

In [ ]:
acidentes.mean(axis=1, keepdims=True).shape

(5, 1)

In [ ]:
acidentes.mean(axis=1).shape

(5,)

In [ ]:
acidentes.cumsum(axis=0) #soma acumulada de acidentes por cliente de todos os anos

array([[1, 3, 2],
       [1, 4, 2],
       [3, 5, 6],
       [3, 5, 6],
       [4, 6, 6]])

In [ ]:
acidentes.cumsum(axis=1) #soma acumulada de acidentes por ano de todos os clientes

array([[1, 4, 6],
       [0, 1, 1],
       [2, 3, 7],
       [0, 0, 0],
       [1, 2, 2]])

**Cartela de Bingo 2**


In [17]:
cartela_bingo = np.random.randint(0,10, (4,4))
cartela_bingo

array([[4, 1, 1, 8],
       [1, 0, 1, 6],
       [0, 7, 8, 8],
       [8, 6, 3, 6]])

In [19]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[4, 1, 1, 8],
       [1, 0, 1, 6],
       [0, 7, 8, 8]])

In [20]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

array([[8, 6, 3, 6]])

In [21]:
np.concatenate((cartela_bingo1, cartela_bingo2))

array([[4, 1, 1, 8],
       [1, 0, 1, 6],
       [0, 7, 8, 8],
       [8, 6, 3, 6]])

In [22]:
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
np.delete(cartela_bingo, 1, axis=1) #eixo 1 é sempre as colunas

array([[4, 1, 8],
       [1, 1, 6],
       [0, 8, 8],
       [8, 3, 6]])

In [27]:
np.delete(cartela_bingo, 1, axis=0) #eixo 0 é sempre as linhas

array([[4, 1, 1, 8],
       [0, 7, 8, 8],
       [8, 6, 3, 6]])

**Aritmetica**

In [28]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
arr += 3
arr

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2 *= 5
arr2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
a = np.array([[1, 2, 3], [4,5,6]]) #operaçao permitida pelo numpy pq os arrays a e b tem o mesmo tamanho
b = np.array([[2,2,2], [0,0,1]])
a+b

array([[3, 4, 5],
       [4, 5, 7]])

In [35]:
c = np.array([[1, 2, 3], [4,5,6]])
d = np.array([[2,2,2], [0,0,1]])
a*b

array([[2, 4, 6],
       [0, 0, 6]])

In [36]:
a = np.array([[1, 2, 3], [4,5,6]])
a > 3

array([[False, False, False],
       [ True,  True,  True]])

In [37]:
arr = np.array(["Hello", "Girls", "Womakerscode"]) #aqui eu to verificando se a qtidade de elemento desse vetor é maior q 5
len(arr) > 5


False

In [38]:
vetorizar_len = np.vectorize(len) #vetorizando matriz: aplica uma funcao pra cada elemento de um array. Nesse caso, pra cada elemento do vetor é maior que cinco
vetorizar_len(arr) > 5

array([False, False,  True])

### 1. O cliente que teve acidente abaixo da média nos últimos 2 anos, ganhará um desconto no seu seguro. Identifique-os.


### 2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

### 3. Uma professora quer que seus alunos apliquem a função (3x + 2y + x*y) em um conjunto de dados. Ela dá dois arrays aos estudantes e pede que seja feita essa operação.


### 4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e esqueceu de anotar a nota de trabalhos apresentados durante o semestre. Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. No array cada estudante representa uma linha e cada coluna uma prova. Adicione para cada prova de cada estudante os valores: 1, 2, 1.